-- database/seed.sql

USE afaq_portfolio;

-- Seed Admin User (password: adminpass)
INSERT INTO users (username, password, role) VALUES
('admin', '$2b$10$wT0E0Qv3D0Qv3D0Qv3D0Qu.GgT3O.yR.eX.QyR.eX.QyR.eX.QyR.eX.QyR.eX.QyR.eX', 'admin');
-- Note: Replace the hash with a real bcrypt hash for 'adminpass' or similar,
-- generated by a tool or by your backend's hashing utility.
-- Example hash for 'adminpass' (you should generate your own):
-- SELECT '$2b$10$wT0E0Qv3D0Qv3D0Qv3D0Qu.GgT3O.yR.eX.QyR.eX.QyR.eX.QyR.eX.QyR.eX.QyR.eX' AS hashed_password;
-- (This is just an example. You'll generate it in authController)

-- Seed Projects
INSERT INTO projects (title, description, tech_stack, github_url, live_demo_url, image_url) VALUES
('AI Chatbot Platform', 'A robust AI-powered chatbot platform with advanced natural language processing capabilities.', '["React", "Node.js", "Express", "MongoDB", "OpenAI API", "LangChain"]', 'https://github.com/afaqahmad/ai-chatbot', 'https://demo.aichatbot.com', 'https://via.placeholder.com/800x600/1e293b/a8c0ff?text=AI+Chatbot'),
('Hospital Management System', 'Comprehensive system for managing hospital operations, patient records, appointments, and billing.', '["Angular", "Spring Boot", "MySQL", "Docker"]', 'https://github.com/afaqahmad/hms', 'https://demo.hms.com', 'https://via.placeholder.com/800x600/0f172a/7c76ff?text=HMS'),
('E-commerce Store', 'Full-featured e-commerce platform with product catalog, shopping cart, payment gateway integration, and admin panel.', '["Next.js", "Stripe", "PostgreSQL", "Tailwind CSS"]', 'https://github.com/afaqahmad/e-commerce', 'https://demo.ecommerce.com', 'https://via.placeholder.com/800x600/172554/7ea3ff?text=E-commerce'),
('Real Estate Platform', 'A modern platform for buying, selling, and renting properties with advanced search and mapping features.', '["Vue.js", "Django", "PostgreSQL", "Mapbox GL JS"]', 'https://github.com/afaqahmad/real-estate', 'https://demo.realestate.com', 'https://via.placeholder.com/800x600/020617/7376fa?text=Real+Estate'),
('CRM Dashboard', 'An intuitive CRM dashboard to manage customer relationships, sales pipelines, and marketing campaigns.', '["React", "Node.js", "Express", "MongoDB", "Charts.js"]', 'https://github.com/afaqahmad/crm-dashboard', 'https://demo.crm.com', 'https://via.placeholder.com/800x600/030712/7679fd?text=CRM+Dashboard');

-- Seed Skills
INSERT INTO skills (category, name, icon_class, order_index) VALUES
('Frontend', 'HTML5', 'fab fa-html5', 1),
('Frontend', 'CSS3', 'fab fa-css3-alt', 2),
('Frontend', 'JavaScript', 'fab fa-js-square', 3),
('Frontend', 'TypeScript', 'devicon-typescript-plain', 4),
('Frontend', 'React', 'fab fa-react', 5),
('Frontend', 'Next.js', 'devicon-nextjs-plain', 6),
('Frontend', 'Tailwind CSS', 'devicon-tailwindcss-plain', 7),
('Backend', 'Node.js', 'fab fa-node-js', 1),
('Backend', 'Express.js', 'devicon-express-original', 2),
('Backend', 'Python', 'fab fa-python', 3),
('Backend', 'Django', 'devicon-django-plain', 4),
('Backend', 'FastAPI', 'devicon-fastapi-plain', 5),
('Databases', 'MySQL', 'devicon-mysql-plain', 1),
('Databases', 'PostgreSQL', 'devicon-postgresql-plain', 2),
('Databases', 'MongoDB', 'devicon-mongodb-plain', 3),
('Cloud & DevOps', 'Git', 'fab fa-git-alt', 1),
('Cloud & DevOps', 'Docker', 'fab fa-docker', 2),
('Cloud & DevOps', 'AWS', 'fab fa-aws', 3),
('AI & Machine Learning', 'OpenAI API', 'devicon-openai-plain', 1),
('AI & Machine Learning', 'LangChain', 'devicon-langchain-plain', 2),
('Tools', 'VS Code', 'devicon-vscode-plain', 1),
('Tools', 'Figma', 'devicon-figma-plain', 2);

-- Seed Services
INSERT INTO services (title, description, icon_class, order_index) VALUES
('Frontend Development', 'Crafting stunning and responsive user interfaces with modern web technologies.', 'fas fa-desktop', 1),
('Backend Development', 'Building robust, scalable, and secure server-side applications and APIs.', 'fas fa-server', 2),
('Full Stack Web Apps', 'End-to-end development of dynamic and interactive web solutions from UI to database.', 'fas fa-globe', 3),
('AI Chatbots', 'Developing intelligent conversational AI agents for various business needs.', 'fas fa-robot', 4),
('SaaS Development', 'Creating scalable Software-as-a-Service applications with multi-tenancy support.', 'fas fa-cloud', 5),
('Database Design', 'Designing efficient and optimized database schemas for high-performance applications.', 'fas fa-database', 6);

-- Seed Testimonials
INSERT INTO testimonials (client_name, client_title, quote, avatar_url, rating) VALUES
('Sarah Johnson', 'CTO, Tech Solutions Inc.', 'Afaq transformed our vision into a stunning reality. His attention to detail and ability to deliver complex features on time was exceptional. Highly recommended!', 'https://randomuser.me/api/portraits/women/68.jpg', 5),
('Michael Chen', 'CEO, Global Innovations', 'Working with Afaq was a fantastic experience. His full-stack expertise and proactive communication made the project seamless and resulted in a product far exceeding our expectations.', 'https://randomuser.me/api/portraits/men/84.jpg', 5),
('Emily White', 'Founder, Creative Agency', 'Afaq’s ability to blend beautiful design with powerful backend functionality is truly impressive. Our new website is not just fast, it\'s a piece of art. Absolutely brilliant!', 'https://randomuser.me/api/portraits/women/44.jpg', 5);

-- Seed initial contact message
INSERT INTO contact_messages (name, email, subject, message) VALUES
('Test User', 'test@example.com', 'Inquiry about project', 'I am interested in discussing a potential project with you. Please get in touch.');